//use npm run api-gen for update this file
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "": {
    get: operations["AppController_getHello"];
  };
  "/knowledge": {
    get: operations["KnowledgeController_getAll"];
  };
  "/knowledge/list": {
    get: operations["KnowledgeController_getList"];
  };
  "/knowledge/{id}": {
    get: operations["KnowledgeController_getDetail"];
  };
  "/admin/knowledge": {
    post: operations["AdminKnowledgeController_createKnowledge"];
  };
  "/admin/knowledge/{id}": {
    put: operations["AdminKnowledgeController_updateKnowledge"];
    delete: operations["AdminKnowledgeController_deleteKnowledge"];
  };
  "/admin/login": {
    post: operations["AdminConrtroller_loginAdmin"];
  };
  "/admin/calendar": {
    post: operations["AdminCalendarController_createKnowledge"];
  };
  "/admin/calendar/{id}": {
    put: operations["AdminCalendarController_updateKnowledge"];
    delete: operations["AdminCalendarController_deleteCalendar"];
  };
  "/calendar": {
    get: operations["CalendarController_getAllCalendar"];
  };
  "/research": {
    get: operations["ResearchController_getAll"];
  };
  "/research/list": {
    get: operations["ResearchController_getList"];
  };
  "/research/{id}": {
    get: operations["ResearchController_getDetail"];
  };
  "/admin/research": {
    post: operations["AdminResearchController_createResearch"];
  };
  "/admin/research/{id}": {
    put: operations["AdminResearchController_updateResearch"];
    delete: operations["AdminResearchController_deleteResearch"];
  };
  "/library": {
    post: operations["AdminLibraryController_createLibrary"];
  };
  "/seed": {
    post: operations["SeedController_seedDatabase"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    KnowledgeAttachmentFullOutputDto: {
      name: string;
      fileName: string;
      path: string;
      mimeType: string;
    };
    KnowledgeFullOutPutDto: {
      id: number;
      title: string;
      body: string;
      knowledgeAttachment?: components["schemas"]["KnowledgeAttachmentFullOutputDto"][];
    };
    KnowledgeListOutPutDto: {
      id: number;
      title: string;
      body: string;
    };
    KnowledgeDto: {
      "files[]": string[];
      /** @description The title */
      title: string;
      body: string;
    };
    HttpResponseDto: {
      status: number;
      message: string;
      data?: Record<string, never>;
    };
    AdminLoginDto: {
      userName: string;
      password: string;
    };
    AdminLoginOutputDto: {
      message: string;
      token: string;
    };
    CalendarDto: {
      "files[]": string[];
      /**
       * Format: date-time
       * @description The title
       */
      dateShow: string;
      text?: string;
    };
    CalendarAttachmentOutputDto: {
      id: number;
      name: string;
      path: string;
      fileName: string;
      mimeType: string;
    };
    CalendarOutputDto: {
      id: number;
      /** Format: date-time */
      dateShow: string;
      text?: string;
      calendarAttachment: components["schemas"]["CalendarAttachmentOutputDto"][];
    };
    ResearchAttachmentFullOutputDto: {
      name: string;
      fileName: string;
      path: string;
      mimeType: string;
    };
    ResearchFullOutPutDto: {
      id: number;
      title: string;
      abstract: string;
      body: string;
      researchAttachment?: components["schemas"]["ResearchAttachmentFullOutputDto"][];
    };
    ResearchListOutPutDto: {
      id: number;
      title: string;
      abstract: string;
      body: string;
    };
    ResearchDto: {
      "files[]": string[];
      /** @description The title */
      title: string;
      body: string;
      abstract: string;
    };
    LibraryDto: {
      "files[]": string[];
      /** @description The title */
      title: string;
      comment?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_getHello: {
    responses: {
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  KnowledgeController_getAll: {
    parameters: {
      query?: {
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeFullOutPutDto"][];
        };
      };
    };
  };
  KnowledgeController_getList: {
    parameters: {
      query?: {
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeListOutPutDto"][];
        };
      };
    };
  };
  KnowledgeController_getDetail: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeFullOutPutDto"];
        };
      };
    };
  };
  AdminKnowledgeController_createKnowledge: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["KnowledgeDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminKnowledgeController_updateKnowledge: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["KnowledgeDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminKnowledgeController_deleteKnowledge: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminConrtroller_loginAdmin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminLoginDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AdminLoginOutputDto"];
        };
      };
    };
  };
  AdminCalendarController_createKnowledge: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CalendarDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminCalendarController_updateKnowledge: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CalendarDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminCalendarController_deleteCalendar: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  CalendarController_getAllCalendar: {
    parameters: {
      query?: {
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CalendarOutputDto"][];
        };
      };
    };
  };
  ResearchController_getAll: {
    parameters: {
      query?: {
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ResearchFullOutPutDto"][];
        };
      };
    };
  };
  ResearchController_getList: {
    parameters: {
      query?: {
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ResearchListOutPutDto"][];
        };
      };
    };
  };
  ResearchController_getDetail: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ResearchFullOutPutDto"];
        };
      };
    };
  };
  AdminResearchController_createResearch: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["ResearchDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminResearchController_updateResearch: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["ResearchDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminResearchController_deleteResearch: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  AdminLibraryController_createLibrary: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["LibraryDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["HttpResponseDto"];
        };
      };
    };
  };
  SeedController_seedDatabase: {
    responses: {
      201: {
        content: never;
      };
    };
  };
}
